# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/repo

    steps:
      - checkout

      - run: pip install --user tox && tox
        environment:
          # Tox is installed into local directory, so add that to path
          PATH: ${PATH}:${HOME}/.local/bin
